import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-linear-to-bl from-slate-800 to-slate-600 via-slate-700 text-white`}
            >
                <div className="w-full bg-orange-400/30 text-yellow-500 shadow-xs border-yellow-600/30 p-2 text-white border-b-2 lg:hidden text-lg">
                  ⚠️ For the best experience, please consider using a desktop device or another device with a larger screen.
                </div>
                {children}
            </body>
        </html>
    );
}
